version: '3.8'

services:
  postgresdb:
    container_name: c_postgresdb
    build:
      context: .
      dockerfile: db.dockerfile
    #restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - app-data:/mnt/app-data
    environment:
      - POSTGRES_DB=ariavt
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    command: -p 5432
    networks:
      - dev-net

  backend:
    build:
      context: .
      dockerfile: backend.dockerfile
    container_name: c_fastapi_backend
    ports:
      - 8000:8000
    volumes:
      - ./:/app_wd
      - app-data:/mnt/app-data
    networks:
      - dev-net
    command: [ "uvicorn", "app.main:app" , "--reload", "--host",
               "0.0.0.0", "--reload-dir", "."]


networks:
  dev-net:
    name: dev-net
    driver: bridge


volumes:
  postgres-data:
    name: postgres-data
  app-data:
    name: app-data
