version: '3.8'

services:
  postgresdb_test:
    container_name: c_postgresdb_test
    build:
      context: .
      dockerfile: db.dockerfile
    restart: always
    environment:
      - POSTGRES_DB=ariavt
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres 
    ports:
      - "5433:5433"
    command: -p 5433
    networks:
      - test-net

  backend_test:
    build:
      context: .
      dockerfile: backend.dockerfile
    container_name: c_fastapi_backend_test
    networks:
      - test-net
    command: >
      sh -c "(python3 -m uvicorn tests.echo_service:service --port 8888 &)
      && python3 -m pytest -s"


networks:
  test-net:
    name: test-net
    driver: bridge