version: '3.8'

services:
  backend_test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: c_fastapi_backend_test
    ports:
      - 8000:8000
    networks:
      - be_dev-net
    command: ["python3", "-m", "pytest", "-s"]

networks:
  be_dev-net:
    external:
      name: dev-net

volumes:
  app-data-test:
    external: true
