version: '3.8'

services:
  backend:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./:/app_wd
      - app-data:/mnt/app-data
    # network_mode: "host"
    networks:
      - be_dev-net

networks:
  be_dev-net:
    external:
      name: dev-net

volumes:
  app-data:
    external: true
