version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: c_fastapi_backend
    ports:
      - 8000:8000
    volumes:
      - ./:/app_wd
      - app-data:/mnt/app-data
    networks:
      - be_dev-net
    command: [ "uvicorn", "app.main:app" , "--reload", "--host",
               "0.0.0.0", "--reload-dir", "."]

networks:
  be_dev-net:
    external:
      name: dev-net

volumes:
  app-data:
    external: true
