#!/bin/bash

extra_args=()
if [ "test" = "$1" ]; then
    DATABASE_URL="postgresql://postgres:postgres@c_postgresdb_test:5433/ariavt"
    extra_args+=(--abort-on-container-exit)
    if [ "--remove-prev" = "$2" ]; then
        docker stop c_postgresdb_test
        docker rm c_postgresdb_test
    fi
elif [ "dev" = "$1" ]; then
    DATABASE_URL="postgresql://postgres:postgres@c_postgresdb:5432/ariavt"
    if [ "--remove-prev" = "$2" ]; then
        docker stop c_postgresdb
        docker rm c_postgresdb
        docker volume rm postgres-data app-data
    fi
elif [ "local" = "$1" ]; then
    DATABASE_URL="postgresql://postgres:postgres@localhost:5433/ariavt"
else
    echo "Error: unknown database."
fi

echo "$DATABASE_URL" > app/database

docker-compose -f backend."$1".yml up --build --force-recreate "${extra_args[@]}"

